### ISSUE TITLE
Unsupported major.minor version 51.0 [Plugin: SmoothScroll]

### ISSUE THREAD

**Issue by KODerFunk** [hccampos/smooth-scroll-plugin#2]
Dont work with last RubyMine (6.0.3)
https://gist.github.com/KODerFunk/8937912
https://gist.github.com/KODerFunk/8937921

**Comment by aboedo** [comment]
same error on pycharm 3.4.1

**Comment by seeruk** [comment]
The solution to this is to change the Java version that your IDE is running as. If you're on OS X for instance, you can open up:

`/Applications/<AppName>.app/Contents` for example: `/Applications/PhpStorm.app/Contents`

Then opening `Info.plist` and search for the JVM version in that file (probably 1.6 by default), and increase it to 1.7 or higher (make sure you have whatever version you specify installed!).

Please note however that this can have some other side effects, as usually this means switching from Apple JVM to an Oracle one.

**Comment by NameFILIP** [comment]
I have the same issue. It would be nice to compile it with 1.6, until IntelliJ uses 1.6 by default.

**Comment by jims** [comment]
Yeah, JetBrains does not recommend using any other JVM than the apple 1.6 on Yosemite yet so that would be awesome. I'd fork and fix it myself but I really suck with java stuff (get lost in xmls jars and classpaths). I find the scrolling in the jetbrains editors irritating so having this would be wonderful! @hccampos Are you still interested in maintaining this plugin?

**Comment by dispeakble** [comment]
Yep. Big cheers for helping. It's much easier to follow code if the scroll
is continuous, not to mention easing. Would be great if the plugin can be
configurable somehow from the settings or a json file. Thanks

**Comment by hccampos** [comment]
Hey guys, I have completely switched to Sublime and haven't used WebStorm or IntelliJ in almost a year.  I would have to dig into their documentation to figure out how to make this stuff work. Also, my Java is getting rusty. So, if anyone wishes to submit a PR or fork it, that would be great.

**Comment by nmaxcom** [comment]
That's a shame. I have the same error popping up, Webstorm 11.0.3, Yosemite 10.11

Most likely same Java issue. But I can't fix it either...

**Comment by hccampos** [comment]
I actually looked at it the other day. Turns out swt's event listener is super crappy and doesn't properly support MacBook's touchpad.

When you scroll either vertically or horizontally it will register as a scroll click which means scrolling gets super annoying and super quick. You scroll diagonally up and the result is that it all cancels out and the screen doesn't move.

The solution would be to write some wrappers for native code that would handle the scroll.

**Comment by seeruk** [comment]
If you guys haven't already done so, I'd recommend that you use the custom JDK that JetBrains now include with their IDEs specifically for OS X, make sure you download the version with it bundled. I also believe there is a smooth-scroll option built in now.

**Comment by opus1269** [comment]
I have put together a plugin inspired by this. I haven't published it, but would appreciate feedback. There is an options dialog under the Tools menu. I've tried it on a couple Windows machines with precision and regular touchpads and a mouse wheel In IntelliJ Community and Android Studio. There is a .jar file at the top level you can grab and install locally.

[Smooth Scroller](https://github.com/opus1269/smooth-scroller)
